minecraft_version=1.21.11
yarn_mappings=1.21.11+build.6
loader_version=0.16.14
fabric_api_version=0.141.6+1.21.11
loom_version=1.9.9

mod_version=0.1.0
maven_group=com.krox
archives_base_name=krox-client

org.gradle.jvmargs=-Xmx1g -XX:MaxMetaspaceSize=256m
# org.gradle.parallel=true  # disabled for low mem
